name: my_lu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/lu.jpeg
    - assets/reg.jpeg
    - assets/campus.jpeg
    - assets/chat.jpg
    - assets/result.jpg
    - assets/routine.jpg
    - assets/setting.jpg
    - assets/info.png
    - assets/logo.jpeg

