name: my_lu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.2
  firebase_core: ^4.1.1
  url_launcher: ^6.3.1
  record: ^6.1.1
  path_provider: ^2.1.4
  flutter_sound: ^9.4.9
  permission_handler: ^12.0.1
  audioplayers: ^6.5.1
  http: ^1.2.2
  path: ^1.9.0
  image_picker: ^1.1.2
  file_picker: ^10.3.3
  intl: ^0.20.2
  google_maps_flutter: ^2.13.1
  google_fonts: ^6.2.1
  share_plus: ^10.0.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/lu.jpeg
    - assets/reg.jpeg
    - assets/campus.jpeg
    - assets/chat.jpeg
    - assets/result.jpeg
    - assets/routine.webp
    - assets/notice.webp
    - assets/info.png
    - assets/bus.png
    - assets/logo.jpeg
    - assets/chat_bg.jpeg
    - assets/campus_map.png
    - assets/lu_info.jpeg
    - assets/uni.jpeg