// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUkjnU3fpkTpjV3WehYdHaNJlgrBbMCi4',
    appId: '1:162266588201:web:d89c09b517844486b46838',
    messagingSenderId: '162266588201',
    projectId: 'my-lu-2eef3',
    authDomain: 'my-lu-2eef3.firebaseapp.com',
    storageBucket: 'my-lu-2eef3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlzxyWn-Z6awt73aa7pW9uVh4I9wj4MBk',
    appId: '1:162266588201:ios:8c21a87801a6a86cb46838',
    messagingSenderId: '162266588201',
    projectId: 'my-lu-2eef3',
    storageBucket: 'my-lu-2eef3.firebasestorage.app',
    iosBundleId: 'com.example.myLu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlzxyWn-Z6awt73aa7pW9uVh4I9wj4MBk',
    appId: '1:162266588201:ios:8c21a87801a6a86cb46838',
    messagingSenderId: '162266588201',
    projectId: 'my-lu-2eef3',
    storageBucket: 'my-lu-2eef3.firebasestorage.app',
    iosBundleId: 'com.example.myLu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUkjnU3fpkTpjV3WehYdHaNJlgrBbMCi4',
    appId: '1:162266588201:web:bc54bab4d970fbb6b46838',
    messagingSenderId: '162266588201',
    projectId: 'my-lu-2eef3',
    authDomain: 'my-lu-2eef3.firebaseapp.com',
    storageBucket: 'my-lu-2eef3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg9KueoRCqQ93CV0hFJ29XZit2KqQeIus',
    appId: '1:162266588201:android:f9c55ab971e43a03b46838',
    messagingSenderId: '162266588201',
    projectId: 'my-lu-2eef3',
    storageBucket: 'my-lu-2eef3.firebasestorage.app',
  );

}